- name: Copy and run JAR file on another Docker container
  hosts: localhost
  become: true
  vars:
    source_container_name: "jenkins-container"
    destination_container_name: "deployment-container"
    source_file_path: "/created_files"
    destination_file_path: "/shared/target"
  tasks:
    - name: Copy file into existing container
      command: cp -r /created_files /shared/target
    - name: Run JAR file on target container
      command: curl --location 'http://deployment-container:5001/execute' --form 'command="java -jar /shared/target/*.jar"'
